kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: squid
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: squid:latest
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/bradmwilliams/squid-cache-openshift.git
      ref: main
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
      imageOptimizationPolicy: SkipLayers
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ConfigChange
